### ISSUE TITLE
`finished` callback invoked before the op is getting .finished state

### ISSUE THREAD

**Issue by purrrminator** [pluralsight/PSOperations#15]
would it be better to move this line:
https://github.com/pluralsight/PSOperations/blob/e8c1387f373d586560ccfa48feb9ddd34cc04fe5/PSOperations/Operation.swift#L345
below this one:
https://github.com/pluralsight/PSOperations/blob/e8c1387f373d586560ccfa48feb9ddd34cc04fe5/PSOperations/Operation.swift#L351

**Comment by MarkQSchultz** [comment]
Is this causing undesired or unexpected behavior?

**Comment by purrrminator** [comment]
yes because I use `finished` callback and check inside the callback whether my OperationQueue has unfinished operations (op.state == .finished)

**Comment by MarkQSchultz** [comment]
After reviewing the code and the documentation for `NSOperationQueue`, we believe there may be a better way to do what you're wanting. According to the docs for the `operations` property of `NSOperationQueue`:
> You can use this property to access the operations queued at any given moment. Operations remain queued until they finish their task. Therefore, the array may contain operations that are executing or waiting to be executed. The list may also contain operations that were executing when the array was initially retrieved but have subsequently finished.
>
> You may monitor changes to the value of this property using key-value observing. Configure an observer to monitor the operations key path of the operation queue.

In other words, if the `operations` array is not empty, it means that there are operations that have not finished (as of the time that the array was created). You can also use KVO to observe this property. It might make more sense to do that, rather than use the `finished()` method to check the state of the operation.

We feel that these are viable options, and would be less risky than changing the order of method calls in the code.

We will be closing this issue, but feel free to continue discussion on it. Our minds could be changed I'm sure.
