### ISSUE TITLE
Swift 3?

### ISSUE THREAD

**Issue by ideity** [pluralsight/PSOperations#79]
Are there any plans to update this for Swift 3?

**Comment by MarkQSchultz** [comment]
We do have a swift3 branch. We have not yet merged it into master. We still need to decide if we want to rename the classes from `Operation` -> `PSOperation`, since the `Foundation` class changed from `NSOperation` to `Operation`. That caused a conflict in naming. The workaround is to use the `PSOperation` typealias or to explicitly type each operation (i.e. `PSOperations.Operation`).

**Comment by ideity** [comment]
Can't wait to see what comes of it!.

**Comment by MarkQSchultz** [comment]
We will be making this change today and hopefully merging it into `master`

**Comment by agiguere** [comment]
Have you decide to rename the class or use the type alias ? 

I think it's more clean to rename it to PSOperation ...

**Comment by msaflund** [comment]
Using type aliases. Why do I get errors for all PSOperation types like below?
"'Operation' is ambiguous for type lookup in this context."

**Comment by MarkQSchultz** [comment]
Hey @msaflund. You'll have to make sure that any object or method signature that uses `Operation` is disambiguated, either by changing it to `PSOperation`, `PSOperations.Operation`, or `Foundation.Operation`.

**Comment by MarkQSchultz** [comment]
And now I'm closing this issue as Swift 3 support is in `master`. If anyone needs additional help or has questions, let's move it to a new issue.
